spring.application.name=xian-The-Big-Fourt-Portfolio-Manager
server.port=9001
spring.datasource.url=jdbc:mysql://localhost:3306/portfolio_db?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=n3u3da!
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.sql.init.mode=always
spring.sql.init.encoding=UTF-8
yahoo.finance.base-url=https://c4rm9elh30.execute-api.us-east-1.amazonaws.com/default/cachedPriceData
